# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('dev_name', models.CharField(max_length=100)),
                ('firmware', models.CharField(max_length=100)),
                ('wireless_mode', models.CharField(max_length=100)),
                ('signal', models.IntegerField()),
                ('ccq', models.IntegerField()),
                ('air_q', models.IntegerField()),
                ('air_c', models.IntegerField()),
                ('freq', models.IntegerField()),
                ('uptime', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
                ('last_seen', models.CharField(max_length=100)),
                ('ping', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
            ],
        ),
    ]
