# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='air_c',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='air_q',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ccq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='error',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='freq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_seen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='login',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ping',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='signal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uptime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='wireless_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
